{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'platformio-helpers' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python >=3.6
    - colorama
    - conda-helpers
    - path-helpers

  run:
    - python >=3.6
    - colorama
    - conda-helpers
    - path-helpers

test:
  imports:
    - {{ MODULE_NAME }}
    - {{ MODULE_NAME }}.develop
    - {{ MODULE_NAME }}.upload

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Helper functions, etc. for PlatformIO projects
  # doc_url:  http://platformio-helpers.readthedocs.org

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..
